/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsNewRouteImport } from './routes/assessments/new'
import { Route as AssessmentsAssessmentIdRouteRouteImport } from './routes/assessments/$assessmentId/route'
import { Route as AssessmentsAssessmentIdIndexRouteImport } from './routes/assessments/$assessmentId/index'
import { Route as AssessmentsAssessmentIdSubmissionsNewRouteImport } from './routes/assessments/$assessmentId/submissions/new'
import { Route as AssessmentsAssessmentIdSubmissionsSubmissionIdRouteImport } from './routes/assessments/$assessmentId/submissions/$submissionId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdRouteRoute =
  AssessmentsAssessmentIdRouteRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssessmentsAssessmentIdIndexRoute =
  AssessmentsAssessmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AssessmentsAssessmentIdRouteRoute,
  } as any)
const AssessmentsAssessmentIdSubmissionsNewRoute =
  AssessmentsAssessmentIdSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => AssessmentsAssessmentIdRouteRoute,
  } as any)
const AssessmentsAssessmentIdSubmissionsSubmissionIdRoute =
  AssessmentsAssessmentIdSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AssessmentsAssessmentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRouteRouteWithChildren
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$assessmentId/': typeof AssessmentsAssessmentIdIndexRoute
  '/assessments/$assessmentId/submissions/$submissionId': typeof AssessmentsAssessmentIdSubmissionsSubmissionIdRoute
  '/assessments/$assessmentId/submissions/new': typeof AssessmentsAssessmentIdSubmissionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdIndexRoute
  '/assessments/$assessmentId/submissions/$submissionId': typeof AssessmentsAssessmentIdSubmissionsSubmissionIdRoute
  '/assessments/$assessmentId/submissions/new': typeof AssessmentsAssessmentIdSubmissionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRouteRouteWithChildren
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$assessmentId/': typeof AssessmentsAssessmentIdIndexRoute
  '/assessments/$assessmentId/submissions/$submissionId': typeof AssessmentsAssessmentIdSubmissionsSubmissionIdRoute
  '/assessments/$assessmentId/submissions/new': typeof AssessmentsAssessmentIdSubmissionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/assessments/$assessmentId/'
    | '/assessments/$assessmentId/submissions/$submissionId'
    | '/assessments/$assessmentId/submissions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessments/new'
    | '/assessments/$assessmentId'
    | '/assessments/$assessmentId/submissions/$submissionId'
    | '/assessments/$assessmentId/submissions/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessments/$assessmentId'
    | '/assessments/new'
    | '/assessments/$assessmentId/'
    | '/assessments/$assessmentId/submissions/$submissionId'
    | '/assessments/$assessmentId/submissions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsAssessmentIdRouteRoute: typeof AssessmentsAssessmentIdRouteRouteWithChildren
  AssessmentsNewRoute: typeof AssessmentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId/': {
      id: '/assessments/$assessmentId/'
      path: '/'
      fullPath: '/assessments/$assessmentId/'
      preLoaderRoute: typeof AssessmentsAssessmentIdIndexRouteImport
      parentRoute: typeof AssessmentsAssessmentIdRouteRoute
    }
    '/assessments/$assessmentId/submissions/new': {
      id: '/assessments/$assessmentId/submissions/new'
      path: '/submissions/new'
      fullPath: '/assessments/$assessmentId/submissions/new'
      preLoaderRoute: typeof AssessmentsAssessmentIdSubmissionsNewRouteImport
      parentRoute: typeof AssessmentsAssessmentIdRouteRoute
    }
    '/assessments/$assessmentId/submissions/$submissionId': {
      id: '/assessments/$assessmentId/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/assessments/$assessmentId/submissions/$submissionId'
      preLoaderRoute: typeof AssessmentsAssessmentIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AssessmentsAssessmentIdRouteRoute
    }
  }
}

interface AssessmentsAssessmentIdRouteRouteChildren {
  AssessmentsAssessmentIdIndexRoute: typeof AssessmentsAssessmentIdIndexRoute
  AssessmentsAssessmentIdSubmissionsSubmissionIdRoute: typeof AssessmentsAssessmentIdSubmissionsSubmissionIdRoute
  AssessmentsAssessmentIdSubmissionsNewRoute: typeof AssessmentsAssessmentIdSubmissionsNewRoute
}

const AssessmentsAssessmentIdRouteRouteChildren: AssessmentsAssessmentIdRouteRouteChildren =
  {
    AssessmentsAssessmentIdIndexRoute: AssessmentsAssessmentIdIndexRoute,
    AssessmentsAssessmentIdSubmissionsSubmissionIdRoute:
      AssessmentsAssessmentIdSubmissionsSubmissionIdRoute,
    AssessmentsAssessmentIdSubmissionsNewRoute:
      AssessmentsAssessmentIdSubmissionsNewRoute,
  }

const AssessmentsAssessmentIdRouteRouteWithChildren =
  AssessmentsAssessmentIdRouteRoute._addFileChildren(
    AssessmentsAssessmentIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsAssessmentIdRouteRoute:
    AssessmentsAssessmentIdRouteRouteWithChildren,
  AssessmentsNewRoute: AssessmentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
