/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsNewRouteImport } from './routes/assessments/new'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments/$assessmentId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/assessments/$assessmentId',
  path: '/assessments/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/new': typeof AssessmentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/assessments/$assessmentId' | '/assessments/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/assessments/$assessmentId' | '/assessments/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessments/$assessmentId'
    | '/assessments/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
